name: shequ
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
      sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
#  simple_slider: ^0.0.1
  carousel_slider: ^1.3.0
  dio: ^2.1.3
  fluttertoast: ^3.0.4
  flutter_html: ^0.9.6
  gzx_dropdown_menu:
    git:
      url: https://github.com/GanZhiXiong/gzx_dropdown_menu.git
  #  amap_location: ^0.2.0
  #  amap_base: ^0.3.5
  shared_preferences: ^0.5.3+4
  multi_image_picker: ^4.5.1
  city_pickers: ^0.1.16
  image_picker: ^0.6.1
  fluwx: ^1.1.1+1
  path_provider: ^1.2.0
  flutter_webview_plugin: ^0.3.7
  amap_location: ^0.2.0
  permission_handler: ^3.2.2
  smooth_star_rating: ^1.0.3
  photo_view: ^0.4.2
  modal_progress_hud: ^0.1.3
  flutter_image_compress: ^0.6.3






dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/weather.png
    - images/search.png
    - images/open_door_background.png
    - images/door.png
    - images/open.png
    - images/open_click.png
    - images/house.png
    - images/life.png
    - images/outseller.png
    - images/see.png
    - images/location.png
    - images/info.png
    - images/selected.png
    - images/cart.png
    - images/cart2.png
    - images/money.png
    - images/visitor.png
    - images/star.png
    - images/order_stay.png
    - images/order_life.png
    - images/order_outseller.png
    - images/moneypacket.png
    - images/visitors.png
    - images/homemember.png
    - images/camera.png
    - images/share.jpg
    - images/outsellerbg.png
    - images/tab1icon.png
    - images/tab2icon.png
    - images/tab4icon.png
    - images/yes.png
    - images/add.png
    - images/needpay.png
    - images/repair.png
    - images/notify.png
    - images/report.png
    - images/address.png
    - images/card.png
    - images/member.png
    - images/single_visitor.png
    - images/weather/100.png
    - images/weather/100n.png
    - images/weather/101.png
    - images/weather/102.png
    - images/weather/103.png
    - images/weather/103n.png
    - images/weather/104.png
    - images/weather/104n.png
    - images/weather/200.png
    - images/weather/201.png
    - images/weather/202.png
    - images/weather/203.png
    - images/weather/204.png
    - images/weather/205.png
    - images/weather/206.png
    - images/weather/207.png
    - images/weather/208.png
    - images/weather/209.png
    - images/weather/210.png
    - images/weather/211.png
    - images/weather/212.png
    - images/weather/213.png
    - images/weather/300.png
    - images/weather/301n.png
    - images/weather/301.png
    - images/weather/302.png
    - images/weather/303.png
    - images/weather/304.png
    - images/weather/305.png
    - images/weather/306.png
    - images/weather/307.png
    - images/weather/309.png
    - images/weather/310.png
    - images/weather/311.png
    - images/weather/312.png
    - images/weather/313.png
    - images/weather/314.png
    - images/weather/315.png
    - images/weather/316.png
    - images/weather/317.png
    - images/weather/318.png
    - images/weather/399.png
    - images/weather/400.png
    - images/weather/401.png
    - images/weather/402.png
    - images/weather/403.png
    - images/weather/404.png
    - images/weather/405.png
    - images/weather/406.png
    - images/weather/406n.png
    - images/weather/407.png
    - images/weather/407n.png
    - images/weather/408.png
    - images/weather/409.png
    - images/weather/410.png
    - images/weather/499.png
    - images/weather/500.png
    - images/weather/501.png
    - images/weather/502.png
    - images/weather/503.png
    - images/weather/504.png
    - images/weather/507.png
    - images/weather/508.png
    - images/weather/509.png
    - images/weather/510.png
    - images/weather/511.png
    - images/weather/512.png
    - images/weather/513.png
    - images/weather/514.png
    - images/weather/515.png
    - images/weather/900.png
    - images/weather/901.png
    - images/weather/999.png


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
